name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1
    - name: Install Dependencies
      run: npm install
    - name: Build the App
      run: npm run build
    - name: Start the App
      run: npm run start
      
