name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/setup-node@v1
    - name: Install Dependencies
      run: yarn install
    - name: Build the App
      run: yarn build
    - name: Start the App
      run: yarn start
      
